server:
  port: ${SERVER_PORT:8086}
  ssl:
    # 开启证书
    enabled: true
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: true
  forward-headers-strategy: framework
  shutdown: graceful
spring:
  application:
    name: ${SERVICE_ID:laokou-generator}
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgresql:5432/kcloud_platform?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-generator&useSSL=false
          username: root
          password: laokou123
        domain:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgresql:5432/kcloud_platform_domain?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-generator&useSSL=false
          username: root
          password: laokou123
        iot:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgresql:5432/kcloud_platform_iot?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-generator&useSSL=false
          username: root
          password: laokou123
        generator:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgresql:5432/kcloud_platform_generator?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-generator&useSSL=false
          username: root
          password: laokou123

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

logging:
  config: classpath:log4j2-test.xml
