auth:
  filter:
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
  username: '@SENTINEL-USERNAME@'
  password: '@SENTINEL-PASSWORD@'
logging:
  file:
    name: logs/csp/sentinel-dashboard.log
  level:
    org:
      springframework:
        web: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
sentinel:
  dashboard:
    version: '@project.version@'
server:
  port: ${SERVER_PORT:8972}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        name: sentinel_dashboard_cookie
  shutdown: graceful
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 512
    # 每块buffer的空间大小
    buffer-size: 2048
    # 分配堆外内存
    direct-buffers: true
    accesslog:
      enabled: true
  ssl:
    enabled: false
spring:
  application:
    name: ${SERVICE_ID:laokou-sentinel}
  profiles:
    active: @PROFILE-ACTIVE@
