scrape_configs:
  - job_name: 'laokou-auth'
    scrape_interval: 2s
    scheme: https
    metrics_path: '/actuator/prometheus'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['auth:1111']
  - job_name: 'laokou-admin'
    scrape_interval: 2s
    scheme: https
    metrics_path: '/actuator/prometheus'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['admin:9990']
